### ISSUE TITLE
setTimeout in the DOM returns a number, not NodeJS.Timeout

### ISSUE THREAD

**Issue by JacobMGEvans** [OpenSourceRaidGuild/SlickGrid#14]
setTimeout in the dom returns a number, not NodeJS.Timeout

_Originally posted by @rbusquet in https://github.com/OpenSourceRaidGuild/SlickGrid/pull/13#discussion_r608782960_

**Comment by JacobMGEvans** [comment]
@YPAzevedo

**Comment by rbusquet** [comment]
made a little digging and looks like it can be caused by having `"types": ["node"]`  in the tsconfig.json, which is the case for the project... should we remove that? https://stackoverflow.com/questions/45802988/typescript-use-correct-version-of-settimeout-node-vs-window
